# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q-zwf_QUldjksjSDPCTsEitYrtzr56aG
"""



1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.

n1 = 12
print(n1*n1)

2 -crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.

nome = "Lucio"
sobrenome = "caires"
print(nome, sobrenome)

3 -Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.

n2 = 10
n3 = 20
print(n2,n3)

4 -Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.

texto = "python"
n4 = 14
print(texto,n4)

5 -Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

texto2 = "escola"
texto3 = input("escreva uma palavra")
print(texto2, texto3)


6 -Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".**

hora= 10
minuto = 26
segundos = 36
print(hora,":",minuto,":",segundos)